"use strict";
(()=>{
const I='icons/';const THEMES=[['soft','نرم'],['oled','OLED'],['midnight','Midnight'],['forest','Forest'],['violet','Violet'],['ice','Ice'],['sunset','Sunset'],['warm','گرم'],['paper','Paper'],['contrast','Contrast']];
const MAP=[[/خانه|داشبورد/,'home'],[/برنامه/,'plan'],[/آزمون|تست/,'test'],[/مرور/,'review'],[/تنظیم/,'settings'],[/خروجی|export/i,'export'],[/ورودی|import/i,'import'],[/بعدی|بعد/,'next'],[/قبلی|قبل/,'previous'],[/شروع/,'start'],[/مکث|توقف/,'pause'],[/Submit|ثبت|ارسال/i,'check'],[/پرچم|نشان/,'flag']];
function img(n){const x=document.createElement('img');x.className='proIcon';x.src=I+n+'.svg';x.alt='';x.setAttribute('aria-hidden','true');return x}
function deco(b,n){if(!b)return;const has=b.querySelector('.proIcon');if(b.dataset.proIconized===n&&has)return;const label=((has?b.dataset.proLabel:'')||b.getAttribute('aria-label')||b.textContent||'').trim().replace(/[\u25B6\u275A\u2690\u2691\u2705\u274C\u{1F3AF}\u{1F4DA}]/gu,'');b.dataset.proLabel=label;b.dataset.proIconized=n;b.replaceChildren(img(n));if(label&&b.id!=='focusPlayBtn'){const s=document.createElement('span');s.className='proLabel';s.textContent=label;b.append(s)}if(label&&!b.getAttribute('aria-label'))b.setAttribute('aria-label',label)}
const LEGACY={"\u{1F3AF}":'calendar',"\u{1F4DA}":'import',"\u2705":'correct',"\u274C":'wrong',"\u2691":'flag',"\u2690":'flag',"\u23ED":'next'};
function replaceLegacy(){if(!document.body)return;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){const t=n.nodeValue||'';if(!Object.keys(LEGACY).some(k=>t.includes(k)))continue;const f=document.createDocumentFragment();let buf='';for(const ch of t){const icon=LEGACY[ch];if(icon){if(buf){f.append(document.createTextNode(buf));buf=''}f.append(iconImg(icon))}else buf+=ch}if(buf)f.append(document.createTextNode(buf));n.replaceWith(f)}}
function decorate(){deco(document.getElementById('quickTheme'),'themes');const f=document.getElementById('focusPlayBtn');if(f)deco(f,f.dataset.iconName||'start');document.querySelectorAll('button').forEach(b=>{if(b.id==='focusPlayBtn'||b.id==='quickTheme')return;const t=((b.querySelector('.proIcon')?b.dataset.proLabel:'')||b.textContent||'').trim();for(const [r,n] of MAP)if(r.test(t)){deco(b,n);break}})}
function themes(){const s=document.getElementById('themeSelect');if(!s||document.getElementById('proThemeGrid'))return;const g=document.createElement('div');g.id='proThemeGrid';g.className='proThemeGrid';THEMES.forEach(([v,l])=>{const b=document.createElement('button');b.type='button';b.className='proThemeCard';b.dataset.theme=v;b.setAttribute('aria-label','تم '+l);b.innerHTML=`<span class="proThemeSwatch" data-theme="${v}"><i></i><i></i><i></i></span><span>${l}</span>`;b.onclick=()=>{s.value=v;s.dispatchEvent(new Event('change',{bubbles:true}));sync()};g.append(b)});s.parentElement?.append(g);sync()}
function sync(){const s=document.getElementById('themeSelect');if(s)document.querySelectorAll('.proThemeCard').forEach(b=>b.classList.toggle('active',b.dataset.theme===s.value))}
function art(){const q=document.querySelector('#roundSummary .panel,#roundSummary .card,#summaryView .panel,#summaryView .card');if(q&&!q.querySelector('.proIllustration')){const x=document.createElement('img');x.src='illustrations/round_complete.svg';x.alt='';x.className='proIllustration';q.prepend(x)}document.querySelectorAll('.empty,.emptyState').forEach(e=>{if(!e.querySelector('.proEmptyIllustration')){const x=document.createElement('img');x.src='illustrations/empty_state.svg';x.alt='';x.className='proEmptyIllustration';e.prepend(x)}})}
function splash(){if(document.getElementById('proSplash')||!document.body)return;const e=document.createElement('div');e.id='proSplash';e.setAttribute('aria-hidden','true');e.innerHTML='<img src="illustrations/splash.svg" alt=""><span>Radiology 1405</span>';document.body.append(e);setTimeout(()=>e.classList.add('out'),340);setTimeout(()=>e.remove(),900)}
function go(){replaceLegacy();decorate();themes();sync();art()}const m=new MutationObserver(go);m.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['data-icon-name','class']});document.addEventListener('DOMContentLoaded',()=>{splash();go()});if(document.body){splash();go()}
})();
