'use strict';
(()=>{
const EXTRA_DEFAULTS={adhdMode:true,density:'comfortable',sfx:true,sfxVolume:45,haptics:true,hapticLevel:'medium',focusAudio:false,focusAudioMode:'ambient',focusVolume:18,focusTimer:25,reduceGlow:false,glass:true};
const THEME_ORDER=['soft','oled','midnight','forest','violet','ice','sunset','warm','paper','contrast'];
const EXTRA_THEMES=['theme-oled','theme-midnight','theme-forest','theme-violet','theme-ice','theme-sunset'];
const AUDIO_TITLES={ambient:'Ambient Pad',rain:'باران نرم',brown:'Brown Noise',pulse:'Calm Pulse'};
let audio={ctx:null,focusGain:null,nodes:[],pulseTimer:null},focusTimerEnds=0,focusTimerTick=null,timerStarted=false;
const feedbackSeen=new Set(),summarySeen=new Set();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

function mergeState(v){const d=defaultState(),x=v||{};return Object.assign(d,x,{settings:Object.assign({},d.settings,EXTRA_DEFAULTS,x.settings||{})})}
const baseDefaultState=defaultState;
defaultState=function(){const d=baseDefaultState();d.settings=Object.assign({},EXTRA_DEFAULTS,d.settings||{});if(!d.settings.motion||d.settings.motion==='dynamic')d.settings.motion='snappy';if(d.settings.breakEvery===40)d.settings.breakEvery=30;return d};
loadState=function(){try{if(window.AndroidBridge?.loadProgress){const raw=window.AndroidBridge.loadProgress();if(raw)return mergeState(JSON.parse(raw))}}catch(e){console.warn('native load',e)}try{return mergeState(JSON.parse(localStorage.getItem(SKEY)))}catch(_){try{return mergeState(JSON.parse(localStorage.getItem(PREVKEY)))}catch(__){return defaultState()}}};

function settingsMarkup(){return `
<div class="settingGroup"><div class="settingGroupTitle">ظاهر <span>تم، خوانایی، چگالی</span></div><div class="settingsGrid two">
<div class="setting"><label>تم مطالعه</label><select id="themeSelect"><option value="soft">سیاه نرم</option><option value="oled">OLED مشکی خالص</option><option value="midnight">Midnight آبی</option><option value="forest">Forest سبز</option><option value="violet">Violet بنفش</option><option value="ice">Ice خاکستری-آبی</option><option value="sunset">Sunset گرم</option><option value="warm">شب گرم</option><option value="paper">کاغذی گرم</option><option value="contrast">کنتراست بالا</option></select><small>تم فقط رنگ نیست؛ کنتراست پنل، مرزها و حالات پاسخ هم هماهنگ می‌شوند.</small></div>
<div class="setting"><label>فونت خواندن</label><select id="fontFamily"><option value="system">سیستمی روان</option><option value="readable">Tahoma خوانا</option><option value="book">کتابی / نسخ</option></select><small>همه محلی؛ چیزی از اینترنت دانلود نمی‌شود.</small></div>
<div class="setting"><label>اندازه متن: <span id="fontScaleText">100%</span></label><input id="fontScale" type="range" min="90" max="140" step="5" value="100"></div>
<div class="setting"><label>چگالی صفحه</label><select id="densitySelect"><option value="comfortable">راحت و باز</option><option value="compact">فشرده</option></select></div>
</div></div>
<div class="settingGroup"><div class="settingGroupTitle">تمرکز و ADHD-friendly <span>کاهش اصطکاک، نه ادعای درمان</span></div><div class="settingsGrid two">
<div class="setting"><label>مدل مطالعه</label><select id="studyProfile"><option value="smart">هوشمند متعادل</option><option value="safety">Safety تهاجمی</option><option value="deep">تمرکز عمیق</option><option value="exam">آزمونی سخت</option></select><small>فقط انتخاب سؤال را تغییر می‌دهد؛ بانک دست‌نخورده می‌ماند.</small></div>
<div class="setting"><label>انیمیشن</label><select id="motionSelect"><option value="minimal">حداقلی</option><option value="calm">آرام</option><option value="snappy">سریع و واکنشی</option><option value="dynamic">پویا</option><option value="lively">زنده، بدون چشمک</option></select><small>هیچ انیمیشن بی‌پایان یا چشمک‌زن در تست وجود ندارد.</small></div>
<div class="setting inline"><div><label>حالت ADHD-friendly</label><small>متادیتای فرعی کمتر، هدف فعلی واضح‌تر و ناوبری تست چسبان.</small></div><label class="switch"><input id="adhdMode" type="checkbox"><span class="slider"></span></label></div>
<div class="setting inline"><div><label>حالت مطالعه طولانی</label><small>کروم کمتر و تمرکز روی یک کار.</small></div><label class="switch"><input id="longMode" type="checkbox"><span class="slider"></span></label></div>
<div class="setting"><label>تایمر تمرکز</label><select id="focusTimer"><option value="0">خاموش</option><option value="15">۱۵ دقیقه</option><option value="25">۲۵ دقیقه</option><option value="45">۴۵ دقیقه</option><option value="60">۶۰ دقیقه</option></select><small>فقط یادآور است؛ تست را متوقف یا قفل نمی‌کند.</small></div>
<div class="setting"><label>یادآور استراحت</label><div style="display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center"><label class="switch"><input id="breakToggle" type="checkbox" checked><span class="slider"></span></label><select id="breakEvery"><option value="15">هر ۱۵ سؤال</option><option value="20">هر ۲۰ سؤال</option><option value="30">هر ۳۰ سؤال</option><option value="40">هر ۴۰ سؤال</option><option value="50">هر ۵۰ سؤال</option></select></div></div>
</div></div>
<div class="settingGroup"><div class="settingGroupTitle">صدا و لمس <span>آفلاین و اختیاری</span></div><div class="settingsGrid two">
<div class="setting inline"><div><label>صدای درست / غلط</label><small>Chime کوتاه؛ بدون فایل خارجی.</small></div><label class="switch"><input id="sfxToggle" type="checkbox"><span class="slider"></span></label></div>
<div class="setting"><label>بلندی افکت: <span id="sfxVolText">45%</span></label><input id="sfxVolume" type="range" min="0" max="100" step="5" value="45"></div>
<div class="setting inline"><div><label>لرزش لمس</label><small>کلیک، درست و غلط بازخورد متفاوت دارند.</small></div><label class="switch"><input id="hapticToggle" type="checkbox"><span class="slider"></span></label></div>
<div class="setting"><label>شدت لرزش</label><select id="hapticLevel"><option value="light">ملایم</option><option value="medium">متوسط</option><option value="strong">قوی</option></select></div>
<div class="setting inline"><div><label>موسیقی / صدای تمرکز</label><small>Ambient، باران، Brown Noise یا Pulse؛ در خود اپ ساخته می‌شود.</small></div><label class="switch"><input id="focusAudioToggle" type="checkbox"><span class="slider"></span></label></div>
<div class="setting"><label>فضای صوتی</label><select id="focusAudioMode"><option value="ambient">Ambient Pad</option><option value="rain">باران نرم</option><option value="brown">Brown Noise</option><option value="pulse">Calm Pulse</option></select></div>
<div class="setting"><label>بلندی پس‌زمینه: <span id="focusVolText">18%</span></label><input id="focusVolume" type="range" min="0" max="60" step="2" value="18"></div>
<div class="setting inline"><div><label>کاهش Glow</label><small>برای مطالعه طولانی و OLED.</small></div><label class="switch"><input id="reduceGlow" type="checkbox"><span class="slider"></span></label></div>
<div class="setting inline"><div><label>Glass / Blur</label><small>روی گوشی ضعیف می‌توان خاموشش کرد.</small></div><label class="switch"><input id="glassToggle" type="checkbox"><span class="slider"></span></label></div>
</div></div>`}

function injectUi(){const grid=document.querySelector('#settingsView .settingsGrid');if(grid)grid.outerHTML=`<div class="settingsGrid">${settingsMarkup()}</div>`;const test=document.querySelector('#testView .qCard');if(test&&!$('focusStrip'))test.insertAdjacentHTML('beforebegin','<div id="focusStrip" class="focusStrip"><span><b id="focusChunk">تمرکز</b> • <span id="focusRemain">شروع</span></span><span id="focusTimerText">بدون تایمر</span></div>');const bottom=$('bottom');if(bottom&&!$('focusPlayer'))bottom.insertAdjacentHTML('beforebegin','<div id="focusPlayer" class="focusPlayer hidden"><button id="focusPlayBtn" title="پخش/توقف">▶</button><div class="fpText"><b id="focusAudioTitle">Ambient Pad</b><span id="focusAudioState">خاموش</span></div><input id="focusQuickVolume" type="range" min="0" max="60" step="2" value="18" aria-label="بلندی صدای تمرکز"></div><div id="feedbackPulse" class="feedbackPulse"></div>')}
injectUi();

function ensureAudio(){try{if(!audio.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audio.ctx=new C()}if(audio.ctx.state==='suspended')audio.ctx.resume();return audio.ctx}catch(e){console.warn('audio',e);return null}}
function beep(freq,dur,vol,type='sine',delay=0){const c=ensureAudio();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,c.currentTime+delay);g.gain.linearRampToValueAtTime(Math.max(.0001,vol),c.currentTime+delay+.012);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+dur);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+dur+.03)}
function playSfx(kind){if(state?.settings?.sfx===false)return;const v=clamp(Number(state?.settings?.sfxVolume??45)/100,0,.75);if(kind==='correct'){beep(523,.18,.20*v);beep(659,.22,.16*v,'sine',.07)}else if(kind==='wrong'){beep(196,.17,.18*v,'triangle');beep(164,.23,.14*v,'triangle',.09)}else if(kind==='select')beep(480,.05,.055*v);else if(kind==='done'){beep(392,.12,.13*v);beep(523,.16,.14*v,'sine',.07);beep(659,.22,.13*v,'sine',.14)}}
function nativeHaptic(kind='tap'){if(state?.settings?.haptics===false)return;try{window.AndroidBridge?.haptic?.(`${kind}:${state?.settings?.hapticLevel||'medium'}`)}catch(e){console.warn('haptic',e)}}
function pulseFeedback(kind){const p=$('feedbackPulse');if(!p||state?.settings?.motion==='minimal')return;p.className='feedbackPulse '+(kind==='correct'?'good':'bad');void p.offsetWidth;setTimeout(()=>p.className='feedbackPulse',650)}
function reviewFeedback(){try{const r=currentRound(),q=currentQ(r,r.reviewIndex),a=attemptFor(r,q.id);if(!q||!a||a.blank)return;const key=`${state.day}|${r.number}|${q.id}|${a.correct?'c':'w'}`;if(feedbackSeen.has(key))return;feedbackSeen.add(key);if(a.correct){playSfx('correct');nativeHaptic('correct');pulseFeedback('correct')}else{playSfx('wrong');nativeHaptic('wrong');pulseFeedback('wrong')}}catch(e){console.warn('feedback',e)}}

function stopFocusAudio(){if(audio.pulseTimer){clearInterval(audio.pulseTimer);audio.pulseTimer=null}for(const n of audio.nodes){try{n.stop?.()}catch(_){}try{n.disconnect?.()}catch(_){}}audio.nodes=[];if(audio.focusGain){try{audio.focusGain.disconnect()}catch(_){}}audio.focusGain=null;updateFocusPlayer()}
function noiseBuffer(c,seconds=3,brown=false){const b=c.createBuffer(1,Math.floor(c.sampleRate*seconds),c.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){const w=Math.random()*2-1;if(brown){last=(last+.02*w)/1.02;d[i]=last*3.4}else d[i]=w}return b}
function startFocusAudio(){stopFocusAudio();if(!state?.settings?.focusAudio)return updateFocusPlayer();const c=ensureAudio();if(!c)return toast('پخش صدا روی این WebView در دسترس نیست');const master=c.createGain();master.gain.value=clamp(Number(state.settings.focusVolume||18)/100,0,.6);master.connect(c.destination);audio.focusGain=master;const mode=state.settings.focusAudioMode||'ambient';if(mode==='ambient'){for(const [hz,vol,type] of [[110,.10,'sine'],[164.81,.035,'triangle'],[220,.035,'triangle']]){const o=c.createOscillator(),g=c.createGain(),lp=c.createBiquadFilter();o.type=type;o.frequency.value=hz;g.gain.value=vol;lp.type='lowpass';lp.frequency.value=700;o.connect(lp).connect(g).connect(master);o.start();audio.nodes.push(o,g,lp)}const lfo=c.createOscillator(),lg=c.createGain();lfo.frequency.value=.07;lg.gain.value=.025;lfo.connect(lg).connect(master.gain);lfo.start();audio.nodes.push(lfo,lg)}else if(mode==='rain'||mode==='brown'){const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=noiseBuffer(c,4,mode==='brown');src.loop=true;f.type=mode==='rain'?'bandpass':'lowpass';f.frequency.value=mode==='rain'?1700:420;f.Q.value=mode==='rain'?.55:.3;g.gain.value=mode==='rain'?.23:.30;src.connect(f).connect(g).connect(master);src.start();audio.nodes.push(src,f,g)}else{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=146.83;g.gain.value=.055;o.connect(g).connect(master);o.start();audio.nodes.push(o,g);audio.pulseTimer=setInterval(()=>{if(state?.settings?.focusAudio)beep(293,.12,.02,'sine')},2000)}updateFocusPlayer()}
function setFocusVolume(v){if(!state)return;state.settings.focusVolume=Number(v);if(audio.focusGain&&audio.ctx)audio.focusGain.gain.setTargetAtTime(clamp(Number(v)/100,0,.6),audio.ctx.currentTime,.05);save();updateFocusPlayer();if($('focusVolume')){$('focusVolume').value=v;$('focusVolText').textContent=`${v}%`}}
function updateFocusPlayer(){if(!state||!$('focusPlayer'))return;const enabled=!!state.settings.focusAudio;$('focusPlayer').classList.toggle('hidden',!enabled);$('focusPlayBtn').textContent=audio.focusGain?'❚❚':'▶';$('focusAudioTitle').textContent=AUDIO_TITLES[state.settings.focusAudioMode]||'Focus Audio';$('focusAudioState').textContent=audio.focusGain?'در حال پخش • آفلاین':'برای پخش لمس کن';$('focusQuickVolume').value=state.settings.focusVolume??18}

function startFocusTimer(reset=false){clearInterval(focusTimerTick);const mins=Number(state?.settings?.focusTimer||0);if(!mins){focusTimerEnds=0;updateFocusStrip();return}if(reset||!focusTimerEnds||focusTimerEnds<Date.now())focusTimerEnds=Date.now()+mins*60000;focusTimerTick=setInterval(updateFocusStrip,1000);updateFocusStrip()}
function ensureTimer(){if(!timerStarted&&state){timerStarted=true;startFocusTimer(true)}}
function updateFocusStrip(){if(!state||!$('focusTimerText'))return;let r=null,i=0;try{if(currentView==='test'){r=currentRound();i=Number(r.currentIndex||0)}}catch(_){}const chunkLeft=r?Math.min(10-(i%10),r.ids.length-i):0;$('focusChunk').textContent=r?`بخش ${faNum(Math.floor(i/10)+1)}`:'تمرکز';$('focusRemain').textContent=r?`${faNum(chunkLeft)} سؤال تا پایان این بخش`:'آماده';if(!focusTimerEnds){$('focusTimerText').textContent='بدون تایمر';return}const left=Math.max(0,focusTimerEnds-Date.now()),m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);$('focusTimerText').textContent=`${faNum(m)}:${String(s).padStart(2,'0')}`;if(left<=0){clearInterval(focusTimerTick);focusTimerEnds=0;toast('تایمر تمرکز تمام شد • ۲ دقیقه از صفحه فاصله بگیر');nativeHaptic('timer');playSfx('done')}}

const baseApply=applySettings;
applySettings=function(){document.body.classList.remove(...EXTRA_THEMES,'motion-snappy','adhd','compact','reduce-glow','glass-off');baseApply();const th=state?.settings?.theme||'soft';if(['oled','midnight','forest','violet','ice','sunset'].includes(th))document.body.classList.add('theme-'+th);if(state?.settings?.motion==='snappy'&&!state.settings.longMode)document.body.classList.add('motion-snappy');document.body.classList.toggle('adhd',state?.settings?.adhdMode!==false);document.body.classList.toggle('compact',state?.settings?.density==='compact');document.body.classList.toggle('reduce-glow',!!state?.settings?.reduceGlow);document.body.classList.toggle('glass-off',state?.settings?.glass===false);updateFocusPlayer();updateFocusStrip()};
const baseRenderSettings=renderSettings;
renderSettings=function(){baseRenderSettings();if(!state)return;$('densitySelect').value=state.settings.density||'comfortable';$('adhdMode').checked=state.settings.adhdMode!==false;$('sfxToggle').checked=state.settings.sfx!==false;$('sfxVolume').value=state.settings.sfxVolume??45;$('sfxVolText').textContent=`${state.settings.sfxVolume??45}%`;$('hapticToggle').checked=state.settings.haptics!==false;$('hapticLevel').value=state.settings.hapticLevel||'medium';$('focusAudioToggle').checked=!!state.settings.focusAudio;$('focusAudioMode').value=state.settings.focusAudioMode||'ambient';$('focusVolume').value=state.settings.focusVolume??18;$('focusVolText').textContent=`${state.settings.focusVolume??18}%`;$('focusTimer').value=String(state.settings.focusTimer||0);$('reduceGlow').checked=!!state.settings.reduceGlow;$('glassToggle').checked=state.settings.glass!==false;updateFocusPlayer()};
const baseShowTest=showTest;showTest=function(){baseShowTest();updateFocusStrip()};
const baseShowReview=showReview;showReview=function(){baseShowReview();reviewFeedback()};
const baseShowSummary=showSummary;showSummary=function(n){baseShowSummary(n);const k=`${state?.day}|${n}`;if(!summarySeen.has(k)){summarySeen.add(k);playSfx('done')}};
const baseShowView=showView;showView=function(v){baseShowView(v);ensureTimer();updateFocusStrip();updateFocusPlayer()};

const baseBind=bind;
bind=function(){baseBind();$('quickTheme').onclick=()=>{const i=THEME_ORDER.indexOf(state.settings.theme||'soft');state.settings.theme=THEME_ORDER[(i+1)%THEME_ORDER.length];save();applySettings();toast('تم تغییر کرد')};$('densitySelect').onchange=e=>{state.settings.density=e.target.value;save();applySettings()};$('adhdMode').onchange=e=>{state.settings.adhdMode=e.target.checked;save();applySettings()};$('sfxToggle').onchange=e=>{state.settings.sfx=e.target.checked;save();if(e.target.checked)playSfx('correct')};$('sfxVolume').oninput=e=>{state.settings.sfxVolume=Number(e.target.value);$('sfxVolText').textContent=`${e.target.value}%`;save()};$('hapticToggle').onchange=e=>{state.settings.haptics=e.target.checked;save();if(e.target.checked)nativeHaptic('tap')};$('hapticLevel').onchange=e=>{state.settings.hapticLevel=e.target.value;save();nativeHaptic('tap')};$('focusAudioToggle').onchange=e=>{state.settings.focusAudio=e.target.checked;save();e.target.checked?startFocusAudio():stopFocusAudio();applySettings()};$('focusAudioMode').onchange=e=>{state.settings.focusAudioMode=e.target.value;save();if(state.settings.focusAudio)startFocusAudio();renderSettings()};$('focusVolume').oninput=e=>setFocusVolume(e.target.value);$('focusTimer').onchange=e=>{state.settings.focusTimer=Number(e.target.value);save();startFocusTimer(true)};$('reduceGlow').onchange=e=>{state.settings.reduceGlow=e.target.checked;save();applySettings()};$('glassToggle').onchange=e=>{state.settings.glass=e.target.checked;save();applySettings()};$('focusPlayBtn').onclick=()=>{if(audio.focusGain)stopFocusAudio();else{state.settings.focusAudio=true;save();startFocusAudio();renderSettings()}};$('focusQuickVolume').oninput=e=>setFocusVolume(e.target.value);document.addEventListener('click',e=>{const target=e.target.closest('button,.opt,.errorChoice,.bnav');if(!target)return;nativeHaptic('tap');if(target.matches('#testOptions .opt'))playSfx('select')},{passive:true});};
})();
